# Generated by Django 5.1 on 2025-11-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0002_fundraiser_owner_pledge_supporter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundraiser',
            old_name='decription',
            new_name='description',
        ),
    ]
