# Generated by Django 5.1 on 2025-11-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0003_rename_decription_fundraiser_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='goal',
            field=models.PositiveIntegerField(),
        ),
    ]
